// Generated by Wrangler on Fri Jul 26 2024 20:19:51 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database
}
